version: '3.4'

services:
  blazorapp1:
    image: blazorapp1    
    build:
      context: .
      dockerfile: BlazorApp1/Dockerfile
    ports:
      - 7018:80

  blazorapp1api:
    image: blazorapp1api
    build:
      context: .
      dockerfile: BlazorApp1Api/Dockerfile
    ports:
      - 7268:80

  monitoring:
    image: monitoring
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
