name: .NET Selenium Tests

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

jobs:
  build:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/BlazorApp1TestProject/BlazorApp1TestProject.csproj

    - name: Build
      run: dotnet build src/BlazorApp1TestProject/BlazorApp1TestProject.csproj --configuration Release

    - name: Test
      run: dotnet test --filter TestCategory=Selenium src/BlazorApp1TestProject/BlazorApp1TestProject.csproj --no-restore --verbosity normal --logger trx --results-directory "BlazorApp1TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: BlazorApp1TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}