name: Security Scan - OWASP ZAP Scan

on:
  schedule:
    - cron: '40 21 * * 3'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: https://magik3a.github.io/dev.bg
        token: ${{ secrets.GITHUB_TOKEN }}