name: Automation Tests - .NET Unit testing

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/BlazorApp1TestProject/BlazorApp1TestProject.csproj

    - name: Build
      run: dotnet build src/BlazorApp1TestProject/BlazorApp1TestProject.csproj --configuration Release

    - name: Test
      run: dotnet test --configuration Release --filter TestCategory=Unit src/BlazorApp1TestProject/BlazorApp1TestProject.csproj --no-restore --verbosity normal --logger trx --results-directory "BlazorApp1TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: BlazorApp1TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          BlazorApp1TestResults/**/*.trx